- name: Provision User Monitoring
  ansible.builtin.include_tasks: provision_monitoring.yml
  when:
    - enable_user_workload_monitoring

- name: Configure User Monitoring
  ansible.builtin.include_tasks: configure_monitoring.yml
  when:
    - enable_user_workload_monitoring
