- name: Provision Pipelines
  ansible.builtin.include_tasks: provision_pipelines.yml
  when:
    - enable_pipelines

- name: Configure 3scale Demo Pipelines
  ansible.builtin.include_tasks: configure_pipelines.yml
  when:
    - enable_pipelines

- name: Delete Pipeline
  ansible.builtin.include_tasks: delete_pipeline.yml
  when:
    - enable_pipelines
