- name: Install 3scale Demo
  hosts: localhost
  vars:
    verify_tls: false
    insecure_skip_tls_verify: true
    threescale_project: demo-3scale
    grafana_project: demo-3scale
    rhsso_project: demo-rhsso
    apps_project: demo-apps
    camel_k_project: demo-apps
    apicurito_project: demo-tools
    microcks_project: demo-tools
    mailhog_project: demo-tools
    apicurio_registry_project: demo-tools
    kafka_project: demo-tools
    cicd_project: demo-cicd
    # 3scale SSO
    threescale_client_id: threescale
    threescale_client_secret: d141e6ca-707a-4de9-a9c2-696d21890b37
    enable_user_workload_monitoring: true
    grafana_password: 3scale
    grafana_user: admin
    microcks_username: microckstester
    microcks_password: microckstester
    enable_pipelines: true
  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server' and 'token' to be defined"
      when:
        - (server is not defined) or (token is not defined) or (server is none) or (token is none)
      ignore_errors: false

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"

    - name: Include RHSSO
      ansible.builtin.include_role:
        name: rhsso

    - name: Include Mailhog
      ansible.builtin.include_role:
        name: mailhog

    - name: Include Grafana
      ansible.builtin.include_role:
        name: grafana

    - name: Include Microcks
      ansible.builtin.include_role:
        name: microcks

    - name: Include Apicurito
      ansible.builtin.include_role:
        name: apicurito

    - name: Include 3scale
      ansible.builtin.include_role:
        name: 3scale

    - name: Include Demo Apps
      ansible.builtin.include_role:
        name: demo-apps

    - name: Include Streams
      ansible.builtin.include_role:
        name: streams

    - name: Include Service Registry
      ansible.builtin.include_role:
        name: apicurio-registry

    - name: Include Tekton
      ansible.builtin.include_role:
        name: tekton
