- name: Install 3scale Demo
  hosts: localhost
  vars:
    verify_tls: false
    insecure_skip_tls_verify: true
    threescale_project: demo-3scale
    grafana_project: demo-3scale
    rhsso_project: demo-rhsso
    apps_project: demo-apps
    camel_k_project: demo-apps
    apicurito_project: demo-tools
    kafka_ns: demo-tools
    kafka_cluster_name: my-cluster
    mailhog_ns: demo-tools
    valkey_ns: demo-3scale
    apicurio_registry_project: demo-tools
    kafka_project: demo-tools
    cicd_project: demo-cicd
    # 3scale SSO
    threescale_client_id: threescale
    threescale_client_secret: d141e6ca-707a-4de9-a9c2-696d21890b37
    enable_user_workload_monitoring: true
    grafana_password: 3scale
    grafana_user: admin
    enable_pipelines: true
  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server' and 'token' to be defined"
      when:
        - (server is not defined) or (token is not defined) or (server is none) or (token is none)
      ignore_errors: false
      tags: [rhsso, threescale, registry, apicurito, tekton, microcks]

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"
      tags: [rhsso, threescale, registry, apicurito, tekton, microcks]

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"
      tags: [rhsso, threescale, registry, apicurito, tekton, microcks]

    - name: Include RHSSO
      ansible.builtin.include_role:
        name: rhsso
        apply:
          tags: [rhsso, threescale]
      tags: [rhsso, threescale]

    - name: Include Mailhog
      ansible.builtin.include_role:
        name: mailhog
        apply:
          tags: [threescale]
      tags: [threescale]

    - name: Include Grafana
      ansible.builtin.include_role:
        name: grafana
        apply:
          tags: [threescale]
      tags: [threescale]

    - name: Include 3scale
      ansible.builtin.include_role:
        name: threescale
        apply:
          tags: [threescale]
      tags: [threescale]

    - name: Include Demo Apps
      ansible.builtin.include_role:
        name: demo-apps
        apply:
          tags: [threescale]
      tags: [threescale]

    - name: Include Kafka
      ansible.builtin.include_role:
        name: kafka
        apply:
          tags: [registry]
      tags: [registry]

    - name: Include Service Registry
      ansible.builtin.include_role:
        name: apicurio-registry
        apply:
          tags: [registry]
      tags: [registry]

    - name: Include Apicurito
      ansible.builtin.include_role:
        name: apicurito
        apply:
          tags: [apicurito]
      tags: [apicurito]

    - name: Include Tekton
      ansible.builtin.include_role:
        name: tekton
        apply:
          tags: [tekton]
      tags: [tekton]
