apiVersion: v1
kind: Secret
metadata:
  name: zync
stringData:
  DATABASE_URL: postgresql://threescale:threescale@zync-postgresql-db:5432/zync_production
  ZYNC_DATABASE_PASSWORD: threescale
type: Opaque