- name: Evaluate project {{ cicd_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ cicd_project }}"

- name: Evalute Pipeline ServiceAccount Permissions
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    definition:
      metadata:
        name: pipeline-edit
        namespace: '{{ apps_project }}'
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
        - kind: ServiceAccount
          name: pipeline
          namespace: '{{ cicd_project }}'

- name: Evaluate PVCs
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', 'tekton_pvc.yml.j2') }}"

# - name: Evaluate Tasks
#   retries: 5
#   delay: 20
#   register: result
#   until:
#     - result.failed == false
#   kubernetes.core.k8s:
#     api_key: '{{ token }}'
#     host: '{{ server }}'
#     validate_certs: false
#     state: present
#     resource_definition: "{{ lookup('template', item) }}"
#   loop: 
#     - tekton_task_buildah.yml.j2
#     - tekton_task_maven_version.yml.j2
#     - tekton_task_argo_sync.yml.j2

# - name: Evaluate HDF Pipelines
#   retries: 5
#   delay: 10
#   register: result
#   until:
#     - result.failed == false
#   kubernetes.core.k8s:
#     api_key: '{{ token }}'
#     host: '{{ server }}'
#     validate_certs: false
#     state: present
#     resource_definition: "{{ lookup('template', 'tekton_pipeline.yml.j2') }}"
#   loop: '{{ hdf_components }}'
